### ISSUE TITLE
NIP-11 is not working on Snort

### ISSUE THREAD

**Issue by Yonle** [barkyq/gnost-relay#7]
![Screenshot_2023_0529_215740](https://github.com/barkyq/gnost-relay/assets/63401712/07849b77-c5e8-4732-9fbc-649a22572b4d)

**Comment by barkyq** [comment]
Not sure exactly what this is about? Let me take a look. It is also possible that NIP-11 has changed since I implemented it here

**Comment by Yonle** [comment]
![Screenshot_2023_0601_075423](https://github.com/barkyq/gnost-relay/assets/63401712/cf214bfb-f2e3-41bb-a700-5cd3dfc562a6)

Looks same.

**Comment by Yonle** [comment]
![Screenshot_2023_0601_080739](https://github.com/barkyq/gnost-relay/assets/63401712/2b6178a7-0665-4511-b282-65a62edee8b7)

Interestingly not only Snort did not want to show info, Nostros also could not show it.

Guess, time to sniff what was asked.

**Comment by Yonle** [comment]
![Screenshot_2023_0601_082028](https://github.com/barkyq/gnost-relay/assets/63401712/9d01fa81-0772-4ccc-9ab4-82c4bece999c)

Ah.

**Comment by barkyq** [comment]
Let me know if it fixed, I may need to change some other headers too...

**Comment by Yonle** [comment]
It is fixed now. Thanks

**Comment by Yonle** [comment]
![Screenshot_2023_0602_075449](https://github.com/barkyq/gnost-relay/assets/63401712/5a1f1d37-aeb9-4749-ad0f-88044b123b17)

**Comment by barkyq** [comment]
Looks great! Glad uyou alerted me to this :)
